# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bogdan Calmac
tagline:          Tech Notes
url:              http://bcalmac.github.io
paginate:         1
baseurl:          /
author:
  name:           Bogdan Calmac
  url:            http://bcalmac.github.io
  email:          bcalmac@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bcalmac/bcalmac.github.io
